
import java.awt.event.FocusEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author n8wil
 */

public class Landscaping extends javax.swing.JFrame {

    /**
     * Creates new form Landscaping
     */
    public Landscaping() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpYdDimensions = new javax.swing.ButtonGroup();
        jtbLawnService = new javax.swing.JTabbedPane();
        pnlOrder = new javax.swing.JPanel();
        lblClientName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblYdDimensions = new javax.swing.JLabel();
        txtWidthDimension = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnGrass = new javax.swing.JRadioButton();
        btnGravel = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnPlaceOrder = new javax.swing.JButton();
        txtLengthDimension = new javax.swing.JTextField();
        txtLength = new javax.swing.JLabel();
        txtWidth = new javax.swing.JLabel();
        btnClearOrder = new javax.swing.JButton();
        txtTitle = new javax.swing.JTextField();
        pnlReciept = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblClientName1 = new javax.swing.JLabel();
        txtReceiptTotal = new javax.swing.JTextField();
        txtReceiptName = new javax.swing.JTextField();
        btnModify = new javax.swing.JButton();
        txtReceiptLengthDimensions = new javax.swing.JTextField();
        lblYdDimensions1 = new javax.swing.JLabel();
        txtReceiptWidthDimensions = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        lblReceiptYardType = new javax.swing.JLabel();
        txtReceiptYardType = new javax.swing.JTextField();
        btnRecords = new javax.swing.JButton();
        txtReceiptTitle = new javax.swing.JTextField();
        pnlRecords = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientDB = new javax.swing.JTable();
        txtTitle1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniClose = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtbLawnService.setName("Order"); // NOI18N

        pnlOrder.setBackground(new java.awt.Color(0, 51, 102));

        lblClientName.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblClientName.setForeground(new java.awt.Color(255, 255, 255));
        lblClientName.setText("Client Name:");

        lblYdDimensions.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblYdDimensions.setForeground(new java.awt.Color(255, 255, 255));
        lblYdDimensions.setText("Yard Dimensions:");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Yard Type Options: ");

        btnGrass.setBackground(new java.awt.Color(255, 255, 102));
        bgpYdDimensions.add(btnGrass);
        btnGrass.setForeground(new java.awt.Color(255, 255, 255));
        btnGrass.setText("Grass - $25");
        btnGrass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrassActionPerformed(evt);
            }
        });

        btnGravel.setBackground(new java.awt.Color(255, 255, 102));
        bgpYdDimensions.add(btnGravel);
        btnGravel.setForeground(new java.awt.Color(255, 255, 255));
        btnGravel.setLabel("Gravel - $15");
        btnGravel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravelActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total:");

        btnPlaceOrder.setText("Place Order ");
        btnPlaceOrder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102), new java.awt.Color(0, 0, 0)));
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        txtLength.setForeground(new java.awt.Color(255, 255, 255));
        txtLength.setText("Length(in Feet)");

        txtWidth.setForeground(new java.awt.Color(255, 255, 255));
        txtWidth.setText("Width(in Feet)");

        btnClearOrder.setText("Clear");
        btnClearOrder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102), new java.awt.Color(0, 0, 0)));
        btnClearOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearOrderActionPerformed(evt);
            }
        });

        txtTitle.setEditable(false);
        txtTitle.setBackground(new java.awt.Color(255, 255, 102));
        txtTitle.setFont(new java.awt.Font("Magneto", 0, 18)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(0, 51, 102));
        txtTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTitle.setText("Nate's Lawn Serivce");
        txtTitle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 102), new java.awt.Color(153, 153, 255), new java.awt.Color(0, 51, 102), new java.awt.Color(204, 204, 0)));
        txtTitle.setSelectedTextColor(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout pnlOrderLayout = new javax.swing.GroupLayout(pnlOrder);
        pnlOrder.setLayout(pnlOrderLayout);
        pnlOrderLayout.setHorizontalGroup(
            pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOrderLayout.createSequentialGroup()
                        .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYdDimensions)
                            .addComponent(lblClientName))
                        .addGap(18, 18, 18)
                        .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlOrderLayout.createSequentialGroup()
                                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLengthDimension, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLength))
                                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlOrderLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(btnGravel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOrderLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtWidth)
                                            .addComponent(txtWidthDimension, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(3, 3, 3)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlOrderLayout.createSequentialGroup()
                        .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGrass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClearOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOrderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        pnlOrderLayout.setVerticalGroup(
            pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClientName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlOrderLayout.createSequentialGroup()
                        .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYdDimensions)
                            .addComponent(txtLengthDimension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWidthDimension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlOrderLayout.createSequentialGroup()
                        .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLength)
                            .addComponent(txtWidth))
                        .addGap(10, 10, 10)
                        .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGrass)
                            .addComponent(jLabel3)
                            .addComponent(btnGravel))))
                .addGap(18, 18, 18)
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOrderLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnClearOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        jtbLawnService.addTab("Order", pnlOrder);

        pnlReciept.setBackground(new java.awt.Color(0, 51, 102));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total:");

        lblClientName1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblClientName1.setForeground(new java.awt.Color(255, 255, 255));
        lblClientName1.setText("Client Name:");

        txtReceiptTotal.setEditable(false);

        txtReceiptName.setEditable(false);

        btnModify.setText("Modify ");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        txtReceiptLengthDimensions.setEditable(false);

        lblYdDimensions1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblYdDimensions1.setForeground(new java.awt.Color(255, 255, 255));
        lblYdDimensions1.setText("Yard Dimensions:");

        txtReceiptWidthDimensions.setEditable(false);

        btnConfirm.setLabel("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        lblReceiptYardType.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblReceiptYardType.setForeground(new java.awt.Color(255, 255, 255));
        lblReceiptYardType.setText("Yard Type:");

        txtReceiptYardType.setEditable(false);

        btnRecords.setLabel("Records");
        btnRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordsActionPerformed(evt);
            }
        });

        txtReceiptTitle.setEditable(false);
        txtReceiptTitle.setBackground(new java.awt.Color(255, 255, 102));
        txtReceiptTitle.setFont(new java.awt.Font("Magneto", 0, 18)); // NOI18N
        txtReceiptTitle.setForeground(new java.awt.Color(0, 51, 102));
        txtReceiptTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtReceiptTitle.setText("Receipt");
        txtReceiptTitle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 102), new java.awt.Color(153, 153, 255), new java.awt.Color(0, 51, 102), new java.awt.Color(204, 204, 0)));
        txtReceiptTitle.setSelectedTextColor(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout pnlRecieptLayout = new javax.swing.GroupLayout(pnlReciept);
        pnlReciept.setLayout(pnlRecieptLayout);
        pnlRecieptLayout.setHorizontalGroup(
            pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRecieptLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRecieptLayout.createSequentialGroup()
                        .addComponent(lblClientName1)
                        .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRecieptLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(btnRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                            .addGroup(pnlRecieptLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(txtReceiptName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnlRecieptLayout.createSequentialGroup()
                        .addComponent(lblYdDimensions1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReceiptLengthDimensions, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReceiptWidthDimensions, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnlRecieptLayout.createSequentialGroup()
                        .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblReceiptYardType))
                        .addGap(50, 50, 50)
                        .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtReceiptYardType, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReceiptTotal))
                        .addGap(231, 231, 231))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRecieptLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtReceiptTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        pnlRecieptLayout.setVerticalGroup(
            pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecieptLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(txtReceiptTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClientName1)
                    .addComponent(txtReceiptName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYdDimensions1)
                    .addComponent(txtReceiptLengthDimensions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReceiptWidthDimensions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReceiptYardType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReceiptYardType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReceiptTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnModify, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConfirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblYdDimensions1.getAccessibleContext().setAccessibleName("Yard Dimensions(Converted to Inches):");

        jtbLawnService.addTab("Receipt", pnlReciept);

        pnlRecords.setBackground(new java.awt.Color(0, 51, 102));

        tblClientDB.setBackground(new java.awt.Color(255, 255, 102));
        tblClientDB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        tblClientDB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblClientDB);

        txtTitle1.setEditable(false);
        txtTitle1.setBackground(new java.awt.Color(255, 255, 102));
        txtTitle1.setFont(new java.awt.Font("Magneto", 0, 18)); // NOI18N
        txtTitle1.setForeground(new java.awt.Color(0, 51, 102));
        txtTitle1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTitle1.setText("Pending Jobs");
        txtTitle1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 102), new java.awt.Color(153, 153, 255), new java.awt.Color(0, 51, 102), new java.awt.Color(204, 204, 0)));
        txtTitle1.setSelectedTextColor(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout pnlRecordsLayout = new javax.swing.GroupLayout(pnlRecords);
        pnlRecords.setLayout(pnlRecordsLayout);
        pnlRecordsLayout.setHorizontalGroup(
            pnlRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecordsLayout.createSequentialGroup()
                .addGroup(pnlRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRecordsLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRecordsLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(txtTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pnlRecordsLayout.setVerticalGroup(
            pnlRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRecordsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        jtbLawnService.addTab("Records", pnlRecords);

        jMenuBar1.setBackground(new java.awt.Color(0, 51, 102));

        mnuFile.setText("File");

        mniClose.setText("Exit");
        mniClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCloseActionPerformed(evt);
            }
        });
        mnuFile.add(mniClose);

        jMenuBar1.add(mnuFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtbLawnService))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtbLawnService)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearOrderActionPerformed
        //clear out the information that is input into the text fields
        //request focus back at the Name textbox.

        txtName.setText("");
        txtLengthDimension.setText("");
        txtWidthDimension.setText("");
        bgpYdDimensions.clearSelection();
        txtTotal.setText("");
        txtName.requestFocus();

    }//GEN-LAST:event_btnClearOrderActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        //take all information from the first page, and bring it over to the receipt page.
        //Bring the user to the Reciept page.
   
        
   
        String customerName = txtName.getText();
        txtReceiptName.setText(customerName);

        String yardLength = txtLengthDimension.getText();
        txtReceiptLengthDimensions.setText(yardLength);

        String yardWidth = txtWidthDimension.getText();
        txtReceiptWidthDimensions.setText(yardWidth);

        if(btnGrass.isSelected())
        txtReceiptYardType.setText("Grass");
        if(btnGravel.isSelected())
        txtReceiptYardType.setText("Gravel");

        String total = txtTotal.getText();
        txtReceiptTotal.setText(total);
        
        if(dataValidations()== 1)
        {
            JOptionPane.showMessageDialog(this, "The order has been processed. Proceed to the Receipt tab to confirm.");
        }
        
        
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnGravelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravelActionPerformed
        
        calcTotal();
    }//GEN-LAST:event_btnGravelActionPerformed

    private void btnGrassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrassActionPerformed
        
        calcTotal();
    }//GEN-LAST:event_btnGrassActionPerformed

    private void btnRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordsActionPerformed
        // TODO add your handling code here:

        //display records on the JTable

        DefaultTableModel tblModel = new DefaultTableModel();
        tblClientDB.setModel(tblModel);

        String[] colTitles = {"Customer ID", "Name", "Landscape Type", "Yard Width", "Yard Length", "Yard Cost"};
        tblModel.setColumnIdentifiers(colTitles);

        LandscapingDB db2 = new LandscapingDB();
        try {
            ArrayList<LandscapingClass>records;

            records = db2.getAll();
            DecimalFormat fmt1 = new DecimalFormat("$,##0.00");
            DecimalFormat fmt2 = new DecimalFormat("0.0");
            for (int i = 0; i < records.size(); i++) {
                LandscapingClass cus = records.get(i);

                Object[] row = {cus.getIdNum(), cus.getClientName(), cus.getLandscapeType(),
                    fmt2.format(cus.getyardLength()), fmt2.format(cus.getyardWidth()),
                    fmt1.format(cus.getYardCost())};

                tblModel.addRow(row);
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error. Database driver not found.", "Driver not found", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error. Database error: "+ ex.getMessage(), "Database Error.", JOptionPane.ERROR_MESSAGE);
        }

        JOptionPane.showMessageDialog(this, "Thank you for requesting our service! You have been added to the Records.");

    }//GEN-LAST:event_btnRecordsActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // Confirmation button to accept the order.

        JOptionPane.showMessageDialog(this, "Order complete. Thank you for doing business with us.");

        String custName = txtReceiptName.getText();
        String landscapeType = txtReceiptYardType.getText();
        double yardWidth = Double.parseDouble(txtReceiptWidthDimensions.getText());
        double yardLength = Double.parseDouble(txtReceiptLengthDimensions.getText());
        double yardCost = Double.parseDouble(txtReceiptTotal.getText());

        //add student info into an object
        LandscapingClass cust = new LandscapingClass(0, custName, landscapeType, yardWidth, yardLength, yardCost);

        //add student object to database.
        LandscapingDB db = new LandscapingDB();
        try {
            db.add(cust);
            JOptionPane.showMessageDialog(this, "Message was successfully written to database.");
            txtReceiptName.setText("");
            txtReceiptYardType.setText("");
            txtReceiptWidthDimensions.setText("");
            txtReceiptLengthDimensions.setText("");
            txtReceiptName.requestFocus();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error. Database driver not found.", "Driver not found", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error. Database error: "+ ex.getMessage(), "Database Error.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        //The customer wants to alter information
        //Direct them to the first pane to correct information.
        JOptionPane.showMessageDialog(this, "Please select the Order Panel to alter your information.");
        pnlOrder.requestFocus();

    }//GEN-LAST:event_btnModifyActionPerformed

    private void mniCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCloseActionPerformed
       System.exit(0);
    }//GEN-LAST:event_mniCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Landscaping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Landscaping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Landscaping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Landscaping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Landscaping().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgpYdDimensions;
    private javax.swing.JButton btnClearOrder;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JRadioButton btnGrass;
    private javax.swing.JRadioButton btnGravel;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnRecords;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jtbLawnService;
    private javax.swing.JLabel lblClientName;
    private javax.swing.JLabel lblClientName1;
    private javax.swing.JLabel lblReceiptYardType;
    private javax.swing.JLabel lblYdDimensions;
    private javax.swing.JLabel lblYdDimensions1;
    private javax.swing.JMenuItem mniClose;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JPanel pnlOrder;
    private javax.swing.JPanel pnlReciept;
    private javax.swing.JPanel pnlRecords;
    private javax.swing.JTable tblClientDB;
    private javax.swing.JLabel txtLength;
    private javax.swing.JTextField txtLengthDimension;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtReceiptLengthDimensions;
    private javax.swing.JTextField txtReceiptName;
    private javax.swing.JTextField txtReceiptTitle;
    private javax.swing.JTextField txtReceiptTotal;
    private javax.swing.JTextField txtReceiptWidthDimensions;
    private javax.swing.JTextField txtReceiptYardType;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtTitle1;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JLabel txtWidth;
    private javax.swing.JTextField txtWidthDimension;
    // End of variables declaration//GEN-END:variables

  

  private void calcTotal(){
        double totalPrice = 0.0; 
         //compress the yard length and width into one variable, then apply it to the totalCosts
        int yardLength = Integer.parseInt(txtLengthDimension.getText());
        int yardWidth = Integer.parseInt(txtWidthDimension.getText());
        double totalYard = 1.25*(yardLength + yardWidth);
        
        if(btnGrass.isSelected())
        {
            totalPrice = 25.00;
            totalPrice+=totalYard;
        }
        else if (btnGravel.isSelected())
        {
            totalPrice = 15.00;   
            totalPrice+=totalYard;
        } 
        else
        {
        JOptionPane.showMessageDialog(this, "Yard option must be selected", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
        DecimalFormat fmt =  new DecimalFormat("#,##0.00");
        txtTotal.setText(fmt.format(totalPrice));
    }
  
public int dataValidations() {
String sName = txtName.getText();
String sWidth = txtWidthDimension.getText();
String sLength = txtLengthDimension.getText();
if (btnGrass.isSelected() == false && btnGravel.isSelected() == false) {
JOptionPane.showMessageDialog(this, "Error. Please select the type of yard.",
"Error", JOptionPane.ERROR_MESSAGE);
return 0;
}

if ("".equals(sName)) {
JOptionPane.showMessageDialog(this, "Enter a Name",
"Name Error", JOptionPane.ERROR_MESSAGE);
txtName.requestFocusInWindow();
return 0;
}

if ("".equals(sWidth)) {
JOptionPane.showMessageDialog(this, "Enter a Width",
"Width Error", JOptionPane.ERROR_MESSAGE);
txtWidth.requestFocusInWindow();
return 0;
}

try {
Double.parseDouble(sWidth);

} catch (NumberFormatException e) {
JOptionPane.showMessageDialog(this, "Width must be a number",
"Width Error", JOptionPane.ERROR_MESSAGE);
txtWidth.setText("");
txtWidth.requestFocusInWindow();
return 0;
}
if (Double.parseDouble(sWidth) <= 0) {
JOptionPane.showMessageDialog(this, "Width must be greater than 0",
"Width Error", JOptionPane.ERROR_MESSAGE);
txtLength.setText("");
txtLength.requestFocusInWindow();
return 0;
}

if ("".equals(sLength)) {
JOptionPane.showMessageDialog(this, "Enter a Length",
"Length Error", JOptionPane.ERROR_MESSAGE);

txtLength.requestFocusInWindow();
return 0;
}

try {
Double.parseDouble(sLength);

} catch (NumberFormatException e) {
JOptionPane.showMessageDialog(this, "Length must be a number",
"Length Error", JOptionPane.ERROR_MESSAGE);
txtLength.setText("");
txtLength.requestFocusInWindow();
return 0;

}
if (Double.parseDouble(sLength) <= 0) {
JOptionPane.showMessageDialog(this, "Length must be must be greater than 0",
"Length Error", JOptionPane.ERROR_MESSAGE);
txtLength.setText("");
txtLength.requestFocusInWindow();
return 0;
} else {

return 1;
}
}
}